"""
Application Configuration
Centralized settings management using Pydantic BaseSettings
"""

from pydantic_settings import BaseSettings
from typing import Optional
from functools import lru_cache


class Settings(BaseSettings):
    """
    Application settings loaded from environment variables
    """
    
    # Application
    APP_NAME: str = "NLP-to-SQL Analytics"
    APP_VERSION: str = "1.0.0"
    DEBUG: bool = False
    LOG_LEVEL: str = "INFO"
    
    # AWS Configuration
    AWS_REGION: str = "us-east-1"
    AWS_ACCESS_KEY_ID: Optional[str] = None
    AWS_SECRET_ACCESS_KEY: Optional[str] = None
    
    # AWS Bedrock
    BEDROCK_MODEL_ID: str = "anthropic.claude-3-sonnet-20240229-v1:0"
    BEDROCK_EMBEDDING_MODEL_ID: str = "amazon.titan-embed-text-v1"
    BEDROCK_MAX_TOKENS: int = 2000
    BEDROCK_TEMPERATURE: float = 0.1
    
    # Amazon OpenSearch
    OPENSEARCH_HOST: str = "localhost"
    OPENSEARCH_PORT: int = 9200
    OPENSEARCH_INDEX_NAME: str = "query_templates"
    OPENSEARCH_USERNAME: Optional[str] = None
    OPENSEARCH_PASSWORD: Optional[str] = None
    OPENSEARCH_USE_SSL: bool = True
    
    # Amazon Athena
    ATHENA_DATABASE: str = "apple_analytics"
    ATHENA_WORKGROUP: str = "primary"
    ATHENA_OUTPUT_LOCATION: str = "s3://athena-query-results/"
    ATHENA_MAX_EXECUTION_TIME: int = 300  # seconds
    ATHENA_QUERY_TIMEOUT: int = 60
    
    # AWS Glue
    GLUE_CATALOG_ID: Optional[str] = None
    GLUE_DATABASE: str = "apple_analytics"
    
    # AWS Lake Formation
    LAKE_FORMATION_ENABLED: bool = False
    
    # S3
    S3_DATA_BUCKET: str = "apple-analytics-data"
    S3_TEMPLATE_BUCKET: str = "apple-analytics-templates"
    
    # Redis (ElastiCache)
    REDIS_HOST: str = "localhost"
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: Optional[str] = None
    REDIS_DB: int = 0
    REDIS_TTL: int = 3600  # 1 hour
    REDIS_ENABLED: bool = False
    
    # AWS Cognito
    COGNITO_USER_POOL_ID: Optional[str] = None
    COGNITO_CLIENT_ID: Optional[str] = None
    COGNITO_REGION: Optional[str] = None
    
    # Query Governance
    MAX_QUERY_ROWS: int = 10000
    MAX_QUERY_RUNTIME_SECONDS: int = 300
    MAX_QUERY_COST_USD: float = 10.0
    ALLOWED_TABLES: list = ["sales", "products", "stores", "category", "warranty"]
    FORBIDDEN_KEYWORDS: list = ["DROP", "DELETE", "UPDATE", "INSERT", "TRUNCATE", "ALTER"]
    
    # Template Matching
    SIMILARITY_THRESHOLD: float = 0.75
    MAX_TEMPLATE_RESULTS: int = 3
    
    # MCP Server (runs on a separate port to avoid self-deadlock)
    MCP_SERVER_PORT: int = 8001
    MCP_SERVER_URL: str = "http://localhost:8001/mcp/"
    STRANDS_MODEL_ID: str = "us.anthropic.claude-sonnet-4-20250514-v1:0"

    # AWS_BEARER_TOKEN_BEDROCK : str = "bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tLz9BY3Rpb249Q2FsbFdpdGhCZWFyZXJUb2tlbiZYLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFTSUFRQVFNNUZHWURQMjVFQUI0JTJGMjAyNjAzMTglMkZ1cy1lYXN0LTElMkZiZWRyb2NrJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAzMThUMTAzNjAxWiZYLUFtei1FeHBpcmVzPTQzMjAwJlgtQW16LVNlY3VyaXR5LVRva2VuPUlRb0piM0pwWjJsdVgyVmpFRHNhQ1hWekxXVmhjM1F0TVNKR01FUUNJRW41QnRXeWV0c3NRMzM2S3IwMjlSajlZRDZDeHQlMkZVVHRLdVRwTVRKNzJSQWlBUzZsN2dRJTJCQ2tCblVZbWVnVlkzalRmb3JOaDFGWnl6QWJHYmlyeWZRS1N5ckZCQWdFRUFFYUREQXdNVEV3TURneE9EZzJOQ0lNU0VvTGlEQzB2RFBBbFNEWUtxSUVPSGRrZGgwMWpJeHhkRGNsUGdQVzAzU3B6NSUyQllkeXowSG9IcUxDNGhGNDJsOHRMZTlYJTJGVCUyRmlMN0RwZVM5bTM1TE5CSXFPWHRHZ29xc1g4YyUyRmxNbjZ4alpSMHpMWHVFemN6c3dER2ZLeGclMkZXUll1WndpMCUyRlV4WFJpcW1VWnVmJTJGVSUyRmUwcU1xaGVFdyUyQkttR3FzbldpZzNaR2lZeWFjSnJITVdVTWRzUzZVSFZsdFh2UmtwV1dwZjltWlVDcTBlVm5sTiUyRk51S0U0JTJGTnVLekdLZTd2emclMkY3dkFBJTJCJTJCV3ZLUFVscFZqOEdzem53aTdCaWtRTnZlRkVlWUFiVmhhWjdJTDZPRnNUc1YxSTI3QnJZYiUyRkpYS0NhUDBTeW9IWGkyV3owMnd0Nm5sbHpjOENPd293RGg1NXRTUFlSeWppcmRFb056SXAwYnBRWXplbllLbWFUS29kVXRnSnh5NVp0cWVna2c1biUyQktlWEtDWXZFRndhTXdHajUzcVRMdDN1aDhmOUFhSFdVYk5xTkx6REVZNGlDZUxtUjRLbjlzQlMwbXdYN2lydHBLSjR5b1Z5VHF4eE9aazhNemNEbXV5V1pTNTNTRXdoRmtyVklwOGZiT0xwT0FNT0g2ckhYR2ZhR2k0SWhFUUNDTTRGVSUyQnQlMkZ1YjJ0cFFZUjJYcnpmNk95JTJCVjZGUUI4RGdIck9WVmJlYjI5cWRTMjNPRWs5ZUh1eEQlMkZsJTJGVlFaVXgyJTJGZEw0WGl6NFdVMTBVMUFEUm5kc2ZDOGh4cUw0SWY2cCUyQmRVOGUlMkYwVTU3eXU5Smd5V0M5NndIREYxMUxoQ2VHSlV0V3VmbDE1VFZuc0NacXFUR2Zab2xWejZadld6UTg1dVJaJTJCNVhLOHJDNVNHOHdsd2lOMDk2VlRjMjRYRyUyRlBCREpSM3NEazdLbzEzMGhndTFmZ3duS3VvQ1RUT01GdWZLNXJPOG53cHNodkNhWFpLM1ZNUG4lMkY2YzBHT3NVQ1FFenVrM3BaREVHS0lXUWF2bHgwV25RaThLUmhlaDlub1NqdUxWMGlUOW9rQkYlMkJhbkVZOWdvMWlRUlBlNUttRnVsTGVSTERHWExFeFN4akc0SG1pb1ZzcmEwbE54MWJmWmRWRTl2OXdJY2c2c0xiMThtTzd0N3RYRXhZNXZJSW9oaXRDNDVTbWplT3l0THlOV3hKb3pPJTJGJTJGdEFJY1FXZzdNZGptWiUyRnNPOWtwT3ZrMFRUeW93Wnp2WHlaOEpreVg2cnN4RzYwVFdrN0dyZjZST2xUTG5FYndmOW54aUFXeUtlY2h5NiUyQlRkSWhvRGtibzZqSE1vWVh1RmV2VlFjUHZSajc3WEM1M2dUcUtuN1VYSkxJYlZTQkIwcHFNbjg4ajZPZ2ZjT1NrY1E0Tm1RSXowQTc2Vk5yWjJlJTJCY21NOUZ2NnRjTm9TSlpoUXFDMnkyT1I2YVl3dWRGYjNaWVpUJTJGbGt1emElMkJ6TzdVRm5ZMWxldnlteDlZVmpXN0w1bnIlMkJUWEZucFBDZ3B0U0JPVmljMWclMkJYR2olMkYlMkZoQzVHeldkTHRVQXZtTElRZVRCVXgxTzZmbXZnJTNEJTNEJlgtQW16LVNpZ25hdHVyZT1mNzdlNjU2NzlhZWMzM2FiMWRlMDQyMzcyZjNlZGY0ZGNkZGQ4ZmIxMjQ0MGIxOTJjZGZjMGQwZjI0MzhlYjIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZWZXJzaW9uPTE="
    # AWS_BEARER_TOKEN_BEDROCK : str = "bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tLz9BY3Rpb249Q2FsbFdpdGhCZWFyZXJUb2tlbiZYLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFTSUFRQVFNNUZHWVBSRFBWSzJDJTJGMjAyNjAzMTglMkZ1cy1lYXN0LTElMkZiZWRyb2NrJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAzMThUMTM1OTM0WiZYLUFtei1FeHBpcmVzPTQzMjAwJlgtQW16LVNlY3VyaXR5LVRva2VuPUlRb0piM0pwWjJsdVgyVmpFRDRhQ1hWekxXVmhjM1F0TVNKSU1FWUNJUURLVGNLa29JQVhLJTJGdktFZ1lrbXdYcno4N2I0NmUxbnR0d0x5YnVUbUtaV1FJaEFLJTJGUmVoQTdzQ1JyWUtFeXBKSDhGR1IyT0FkNkRmdkJHdVRZeHNaTGl6V3VLc1VFQ0FjUUFSb01NREF4TVRBd09ERTRPRFkwSWd3dE1uMlMlMkZSUVF3NDJWOUZFcW9nUnM3TDVjb2dyWEtKMkRJV2dYJTJGR2pSNVpYJTJGQ3JFTVZxY2lhNHg2eWcxVHBlQzljQkVpdm9tbmglMkZvdnIlMkZHbGN1RUZhVTdpZndsZ3oxMVR1ckZ2V2ZkM2t4WDJ6ZnYxT0VTMEI0ODAzT05tOVQ0WWlMVm1LZElxN3clMkJkaHdlWXcxb0R2aFlQcGttTXU5M29QQWhrU1RFbXdEanE1OG0lMkZla04zOXVuV2JGczJPWFZSd1J1aURTOGxoR29qNEtUREswMTVBeExJQ1hYdmc3azN1VkJDcyUyRlI1Q1VCY3RYJTJCUnolMkZHdkpzYW12cWlJNmg2eDM0UkxYZE05ZEJmcGxEdk1nJTJCUjd0cWJscWlOTnA0T0c3QiUyRjYwSXlRdkFjMGVjQVNCblg4bGZhZ0JCZzN2bnp2dmNDRk9LMVRCRlFrbHZ6YzdWcTU3OWRjcW05TERzNmVONDJ6eWdWTXBXbHVEZFJDRWVBNURvNnVSbGlKbzNGRkd3aWdqcjdsOXpVRzlzTTZvTER4VmVycGxKejRZa1lTSk5Ea0lOdnA1V2VCdjhrOHhHQW1Xbm0yNkUxVDFuVEZlTndCbTRNamNnUlZLVHBRMkd2THVKVWdWMjVOcWxLSzJ2Vk5DajFoUkh0MldrdkRUMVFEMW5JYzZFZllSTWlBVWEwQ2pqRDloc29lQzdTTjI1c0NvVkp3Tjh4SGtKMmslMkJ2Z1liVlhJVUpGZEJmS2EyQWRyJTJCM0o2Q0FKeEZvQ21odG1CZlhOaUUwWUx2eW9xbGlZSEtqUHRnZ0E4OXVEdVpNNzVjUUtsVjJ6b2pRc0M2aE1EWlBYb21jUndBN3lSVVlrSENHSkhuU0hmQXdtbTAlMkJ0SlB5blN4a0I5U1Q2TTdJUFVhdDdabDMlMkZrblJCSzJMcElSQmd0QVRONXRMd0xxWFZZM1cxdGZjUW5haGt5NVlLaWFLRGJiTGpaeWxEVWt3NnJOajV2ZW40d25OJTJGcXpRWTZ3d0lyVXFGMVhhbU1Sb3ZxV0txRTVmSHFySlFSR1ZsVG1FM25PR0JEMzZ2VUxUeFl1MFBpUldRMnhMZ3ZDaWtBeSUyQlFWT1hMWGxmeFNuaUFZdW9RJTJCakhlU1dEdkp6NnVVJTJGYXVZZVU3Qm9tJTJGTEZiSE5ReExDQiUyQmx0clg1RWpCZ1hRWEFhdGQxcmVOSk9aQjQ3TzltZEtEQ2JyUDJJTHdXRm1QbUxCbHRQSDgwcGhWSXdwQ1pDSmllRWl4NmpLMXJrVDAyZzZaZyUyQjVVdXhqMnhUTlVDJTJGV3J5dWhQOURWZnZkTVVyZUVNT0t3MEFnQXJ1eDQ1RTVLWDdjaGE2RmlVS2tjSHp4TXJ6NlVoaVlqVWhJa0hxTXFaeGolMkJpNkI2ZmRtSEd5U1pxMGwwakROSiUyRiUyRm9FN0Z4RTJyZTJkWFFpYVZqdjJwaTUlMkJ3Nkd3SDFyM2FTYnlSVXlYMkdpWEhJVmJGOG1URDI0aklTb0pnJTJGckMlMkZhNGM2dGRXVkZZWVlhMXpQYiUyQjd3T2t1VzVReElhZzNwQ3AzZXI1UjI0eGkyTW5RQmtSUWgyckRSVEFXdjRNSXZQb0ElM0QlM0QmWC1BbXotU2lnbmF0dXJlPTk1YzU2Y2JhMmYxZGQ1ZGUzNGZhMDM5MmZhNzY4NGI2ZTcwM2ZlYzkyYmYyNTUwODMxMDk3YjI5ODE5YTQ0MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JlZlcnNpb249MQ=="
    AWS_BEARER_TOKEN_BEDROCK : str = "bedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29tLz9BY3Rpb249Q2FsbFdpdGhCZWFyZXJUb2tlbiZYLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFTSUFRQVFNNUZHWU1DM1FKNTVHJTJGMjAyNjAzMTklMkZ1cy1lYXN0LTElMkZiZWRyb2NrJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjAzMTlUMDUxNjU5WiZYLUFtei1FeHBpcmVzPTQzMjAwJlgtQW16LVNlY3VyaXR5LVRva2VuPUlRb0piM0pwWjJsdVgyVmpFRTRhQ1hWekxXVmhjM1F0TVNKR01FUUNJQmdxT2JhY1klMkJsbFZ1RHk1cXQ4empLaVY3JTJGekNUT0xuaEFLVWlLUmlUN2FBaUElMkJFY05tVU11eUUlMkZGQXlTT2Yxem12Z1JCSnIwT1ZYQ1lZMVZ0cDZQMmo4aXJGQkFnV0VBRWFEREF3TVRFd01EZ3hPRGcyTkNJTUxnR05icG5tbmw5NTFxSDVLcUlFU1JUWXJ0T1dVS1VTJTJGWnNBUUpiZnhkU1ZpaDBHNiUyRk5sV0FUdmxDbSUyRm1BQjEydzBUSGJwSnNmWVdBSldDNjBNeGV2S3NnJTJGTmh4VCUyRkMyS1Mxajk0bnhDWjJFNkY5RDRNQWg4SFFoOWdOY240VkNoemt1UnFiWjYlMkJ5b3ZNNkd2dlVBMSUyQnJuUFp2SDN5eThyV1VKUnpidDIxUjNyUlZvMElYV2NHSXElMkZFWjBHJTJGcXE3SHl1ZVhSYmVZN0VkaFpCNk5CSiUyQmE2QUclMkZrRUNlbUN5cSUyQjB4S0tHVEFTbHpCUDlLU0FKM2tNdEhoYkR1V0JPbktIRUQ4bmclMkZueWRGeHFBVTFZa1FranlVZSUyQmQ1WjAzTE1weiUyQjR4JTJCTGV2ZTlqWFlJblNSZXNPOVdGZk1GNTZnT3FNeE9UQXJLQmpQVDJ2QlF1UnFlNEpBd1ZQSTBZTW1wZjJXeVJQQXplNSUyQmpTd0hBWlElMkY2JTJGRUZyRHBhbVRZMWtIVEh6dnBweDdEQndYZWppelNWQmNUd1htcFd0UTAzQm9NalRGWHBVUVVaN3g1am95ZmsycHV5MWpId2JQMHQ5eFM4UHpkUGJxeGJncGJGeUVlNkg0Yk5XSlF5a0JPc09zaFM1Y1klMkZaWkhZRkFlVVMyaWlHV3J3dGdhcG9wUTI5ZGNCSlFtNzVPQmF5dUlpTklWWDBMODZrbUJNM1klMkJzQUFpTEk2Y0tVd0xwVmVXVFJDd280QXN0VUhycmV2QkR1bzVUJTJGRnNxJTJGUHVuZTVJZ3h4ZWZCVVpxT1JUVVlOTU5pY255THE5ek1ybFclMkJvbHpPenlYSkZ6eGtONGlybXUyOWZsRHFEY2EwVE5EbWlFODJlRHVQRFVUeTV0RUJKV1NWZGwlMkJKNG5FVXVEcmMyJTJCZWplSTJhRSUyQkplbnRtTVVyUFlCa0NKMDBBbjBzSGFPd2hBTGI2T0JCRCUyRktRYmFLYmNKUXRKRzllb09xdU1LYU43czBHT3NVQ0cyM2Y1c3Q0WFFKNU9VN3NWTXZNSnF2QW1PS3J0SkFhZiUyQnk1empJa1pGU0o5djhnbXBjRndOZ2FRY3lzNmVmTFQ3blV6M1dlOVNGTXBTJTJGZmlkUW1TVWVMcENQTlg3aWtFZzlQRjlIc28lMkZPWnV0OXVFZW5YUTdzb2RwcnJiWkdHaENIeHVUV1Q2SWxRc1dtdFU2RVFPRmVKQXpHb0FMaXIxMk1HTFNVWEo0QXg5amNnJTJCQ1YyNzVNYkhpamVoU2FNOTB2WGw5TFBBdjU0amVWN0lCTEtYeTdrQ3hpRVFBUmFEVlNLdk83NW9WUmg5SEpGOVpWVWclMkZ2ZlpqYSUyQjM2ZDNPRVFHNVl2bWs2cGptJTJCc05pUThvaXR1eGN6eFZvQTFjbjNDcHMyY2FWYSUyRm5zbnhnVkU1ZEpLUjJ3ZFZYT1dSVnVYQUUlMkI0JTJGckNYR1FKcWJrNDdJblFjc01GWHV4dHVHT0t3RE1yRllYd3JaNjFVd0VhMk5RV01HWU96R01OR2RQbW1CZ2F5Szd6enpBN0FHNEZ2dG5iS3RMUnJ1cG1HRnVkejFNb2FqOGxOTk5Td21xcGclM0QlM0QmWC1BbXotU2lnbmF0dXJlPTFkNjEwZTkyZWU2NTI3YmJjN2IxYTcyYjhkYmIyNDJhZjAwZTZhMmU1YjczM2U2YjUzN2ZkZTBmNjI2MmEyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JlZlcnNpb249MQ=="
    # Mock Mode (for testing without AWS)
    MOCK_MODE: bool = True
    MOCK_DATA_PATH: str = "data/mock/apple_sales_fact.csv"
    
    class Config:
        env_file = ".env"
        case_sensitive = True
        extra = "ignore"


@lru_cache()
def get_settings() -> Settings:
    """
    Returns cached settings instance
    Singleton pattern ensures only one settings object
    """
    return Settings()
